name: Bug
description: Report a defect and track the fix.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the bug.
      placeholder: The API returns ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Fix Acceptance Criteria
      placeholder: |
        - [ ] Root cause fixed
        - [ ] Regression test added
    validations:
      required: true
